### ISSUE TITLE
Coupling vscode-ccls and OpenFOAM leaves errors and no OF-specific suggestions

### ISSUE THREAD

**Issue by mms94** [MaskRay/vscode-ccls#140]
### Observed behavior

I set up VS code to work with OpenFOAM, following this nice article:
https://openfoamwiki.net/index.php/HowTo_Use_OpenFOAM_with_Visual_Studio_Code

However, not everything works, but some things do:

There are jobs:
![image](https://github.com/MaskRay/vscode-ccls/assets/138897428/690639c9-45b0-4957-ac5f-a10dfde21b98)

Picking some random file from the OpenFOAM-repo, I see some errors:
![image](https://github.com/MaskRay/vscode-ccls/assets/138897428/825ec29e-485a-4cd4-b671-9987f2f6d348)

I attach the compile_commands.json as a zip.
[compile_commands.zip](https://github.com/MaskRay/vscode-ccls/files/11983867/compile_commands.zip)

 The folder '/home/moritz/OpenFOAM/openfoam-v2212/build/linux64GccDPInt32Debug/ccls-cache' is roughly 127Mb in size.

### Expected behavior

I would hope to get rid of all the error squiggles and when typing a name get OpenFoam-specific code suggestions.

### Steps to reproduce

I don't know how to. Tried to do the set-up of https://openfoamwiki.net/index.php/HowTo_Use_OpenFOAM_with_Visual_Studio_Code

### System information

* ccls version (`git describe --tags`): 
ccls version 0.20220729-0-g74458915
clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
* OS: 
ubuntu 22.04
* Editor: 
VSCode
* vscode-ccls version (`git describe --tags`): 
v0.1.29

**Comment by mms94** [comment]
I have experimented with variuos settings in vs-code. Maybe someone will see an error. I post the status as is.

my `openfoam.code-workspace`

> {
>     "folders": [
>         {
>             "path": "/home/moritz/OpenFOAM/openfoam-v2212"
>         },
>         {
>             "path": "."
>         }
>     ],
>     "settings": {
>         "ccls.cache.directory":
>         "/home/moritz/OpenFOAM/openfoam-v2212/build/linux64GccDPInt32Debug/ccls-cache",
> 
>         "ccls.misc.compilationDatabaseDirectory":
>         "/home/moritz/OpenFOAM/openfoam-v2212/build/linux64GccDPInt32Debug",
> 
>         "C_Cpp.default.compileCommands":
>     "/home/moritz/OpenFOAM/openfoam-v2212/etc/openfoam wmake -with-bear -s -j",
> 
>         "C_Cpp.autocomplete": "disabled",
>         "C_Cpp.errorSquiggles": "disabled",
>         "C_Cpp.formatting": "disabled",
>         "C_Cpp.intelliSenseEngine": "disabled",
>         
>         "files.associations": {
>             "*.H": "cpp",
>             "*.C": "cpp"
>         },
>     }
> }


my `.vscode/c_cpp_properties.json`

> {
>     "configurations": [
>         {
>             "name": "Linux",
>             "includePath": [
>                 "${workspaceFolder}/**"
>             ],
>             "defines": [],
>             "cStandard": "c17",
>             "cppStandard": "c++98",
>             "intelliSenseMode": "linux-gcc-x64"
>         }
>     ],
>     "version": 4
> }


in my user/settings.json

> {
>     "editor.formatOnPaste": true,
>     "jupyter.askForKernelRestart": false,
>     "python.defaultInterpreterPath": "/bin/python3",
>     "[python]": {
>         "editor.formatOnType": true
>     },
>     "[cpp]": {
>         "editor.wordBasedSuggestions": false,
>         "editor.suggest.insertMode": "replace",
>         "editor.semanticHighlighting.enabled": true,
>         "editor.defaultFormatter": "ccls-project.ccls"
>     },
>     "ccls.completion.include.maxPathSize": 0,
>     "ccls.completion.include.suffixWhitelist": [
>         ".h",
>         ".H",
>         ".C",
>         ".hpp",
>         ".hh"
>     ],
>     "ccls.completion.caseSensitivity": 0,
>     "ccls.completion.detailedLabel": true,
>     "ccls.completion.enableSnippetInsertion": true,
>     "diffEditor.ignoreTrimWhitespace": false,
>     "C_Cpp.vcFormat.newLine.closeBraceSameLine.emptyType": true
> }

**Comment by filippo70** [comment]
I am resuming this topic as it is of interest to me, I would like to ask you if you have solved the problem and if so how.
Thank you in advance
