### ISSUE TITLE
.vscode/ccls_cache as default cache directory

### ISSUE THREAD

**Issue by Yanpas** [MaskRay/vscode-ccls#16]
That will solve an issue with version control systems and won't produce more folders inside root
What do you think?

**Comment by MaskRay** [comment]
I know that cquery uses `.vscode/cquery_cached_index`.

For consistency, I choose to use `std::string cacheDirectory = ".ccls-cache";` in `config.hh` and don't do anything special in clients (I'll remove `ccls-cache-dir` in emacs-ccls when it migrates to the new `lsp.el` interface of lsp-mode). You may or may not have noticed that I don't emphasize customizing the initialization option `cacheDirectory` as it gets a good default.

 The cache directory can be shared among clients: you can index your project in vscode or with `ccls -index` and reuse it in Emacs, Vim, Atom, ...

You may configure the global gitignore file I think it should be too annoying.
```
% cat ~/.config/git/ignore
.ccls-cache
.ccls-root
```
