### ISSUE TITLE
CCLS is not terminated after exit vscode

### ISSUE THREAD

**Issue by Will-GXZ** [MaskRay/vscode-ccls#29]
I just updated to the newest version of ccls and vscode-ccls on github. I found that ccls server is not terminated after I quit vscode, I need to manually kill it. Every time when I quit and re-open vscode, it will start a new ccls process. 

Does anyone have the same issue as mine?

---
OS: macOS: 10.13.6
ccls version 7.0.0 (tags/RELEASE_700/final)
vscode-ccls: 0.1.19

**Comment by MaskRay** [comment]
@Yanpas has observed the same issue. I suspect that ccls hasn't received the `exit` notification.

I don't think lockf is the right solution because a) there is not a single project indicator b) `.ccls` `compile_commands.json` can be updated c) it is difficult to get it portable across platforms d) if two instances do not share `cacheDirectory`, starting multiple instances shouldn't be an issue.

**Comment by Yanpas** [comment]
I usually get dangling ccls instances when I have stucked jobs (Jobs that are always running)

**Comment by Will-GXZ** [comment]
@Yanpas True, if all the current jobs are finished, restart vscode or manually call restart ccls server will terminate the old instance, but if we have jobs stucked, restarting will just create a new instance. 

Sometimes this is really painful, because the project I'm working on usually have 4000+ jobs to index, I usually don't wait all jobs to finish. 

By the way, I saw in the latest commits a "lazy mode" is introduced, however it seems not working on my side. I usually manually add "ccls.index.initialBlacklist": ["."]" in my workspace config file and restart ccls, and manually kill the old instance.

**Comment by Yanpas** [comment]
I've implemeted lasy mode with `[".*"]`, since `.` is not valid regexp.
@MaskRay ccls uses regexp for paths or some kind of globbing?

**Comment by Yanpas** [comment]
I've tried it but didn't notice any difference either. What difference do you observe?

Does ccls log invalid regex met?

**Comment by Will-GXZ** [comment]
> I've tried it but didn't notice any difference either. What difference do you observe?
> 
> Does ccls log invalid regex met?

Ok, I just tried ".*" too, it also works, seems like this is not the reason. Now on my side, "ccls: Restart language server in lazy mode" doesn't work, if I do that, ccls will still index everything. Only manually edit config json file works for me.

**Comment by Yanpas** [comment]
My bad, will fix the bug soon

**Comment by Will-GXZ** [comment]
> My bad, will fix the bug soon

Thank you so much for the work, it's really helpful.

**Comment by Yanpas** [comment]
Must be fixed here https://github.com/MaskRay/vscode-ccls/pull/32

Can't test at the moment since I'm on windows

**Comment by MaskRay** [comment]
`"."` versus `".*"` is not relevant. Both should match every filename (no filename can be empty).

`ccls/src/utils.cc:Matcher` uses `std::regex_search(..., ..., std::regex_constants::match_any)` (similar to JavaScript `/needle/.test("haystack_needle_haystack")`)

Yes, language clients should take care of session management and ensure a single instance for each project (or workspace folder).

For completeness, I want to point out that it is possible to have session conflict (but we usually don't need to worry): if you open two editors which share the same non-empty `cacheDirectory` (empty means purely in-memory and thus no conflict) and don't know each other's session management, when a document is saved, there is a conflict and you may see corrupted global index (`query.hh:struct DB`).

**Comment by Yanpas** [comment]
> language clients should take care of session management 

Doesn't ccls handle stdin eof or socket disconnect? I don't know how it connects to client. On the client side I can send terminate signal. Hope vscode api provides pid and there is a crosdplatform node module

**Comment by Yanpas** [comment]
Added process termination as well as some fixes in #33

**Comment by Will-GXZ** [comment]
@Yanpas CCLS: Restart language server in lazy mode. works fine right now. Thanks.

**Comment by Will-GXZ** [comment]
Thanks, with #33 fix, restart language server works normally, but I noticed that if we use "command + q" (on mac) to exit vscode, ccls will not be terminated. Could you take a look? @Yanpas

**Comment by Yanpas** [comment]
Seems like I found an issue. Fix is in https://github.com/Yanpas/vscode-ccls/tree/deactivation Will test this branch

**Comment by Will-GXZ** [comment]
Hi @Yanpas , I found that sometimes when I exit vscode using "command + q" when ccls has unfinished jobs in queue, ccls server will not terminate. Not sure if someone else has the same issue.

**Comment by Yanpas** [comment]
This should have been fixed in master by https://github.com/MaskRay/vscode-ccls/blob/969ece9adfb8a751abb9d2710d3fea9462abf21f/src/serverContext.ts#L311

I hope that Cmd+Q is graceful shutdown i.e. it calls dispose for Context object of an extension. Can you debug ccls master and vscode-ccls master? I cannot reproduce it.

**Comment by Yanpas** [comment]
Ok, seems like there is some timeout for dispose calls. Dispose coroutine may be interrupted if the promise is not resolved for a long time

**Comment by Yanpas** [comment]
@Will-GXZ No need for debug

Found in `extensionHostMain`.ts folllowing:
```typescript
                const extensionsDeactivated = this._extensionService.deactivateAll();

		// Give extensions 1 second to wrap up any async dispose, then exit in at most 4 seconds
		setTimeout(() => {
			Promise.race([timeout(4000), extensionsDeactivated]).then(() => exit(), () => exit());
		}, 1000);
```

4 seconds should be quiet enough. Try this patch and tell me if it solves issue for you:
```diff
index 901e117..da39c02 100644
--- a/src/serverContext.ts
+++ b/src/serverContext.ts
@@ -303,16 +303,17 @@ export class ServerContext implements Disposable {
   }

   public async stop() {
-    await this.client.stop();
+    const stopPromise = this.client.stop();
     // waitpid was called in client.stop
     if (this.clientPid) {
-      await wait(200);
+      await wait(100);
       try {
         process.kill(this.clientPid, "SIGTERM");
       } catch (e) {
         // no such process
       }
     }
+    return stopPromise;
   }

   private reloadIndex() {

```

What do you observe with 200 milliseconds, 300?
If it fixes issue I will commit `Promise.race` solution

**Comment by Will-GXZ** [comment]
Thanks for the quick response @Yanpas . Most of the time it works, the error occurs occasionally, I also think it's because some issue with time delay. I tried 200 and 300, all works fine, but since the error is not easy to reproduce, I do suggest to add more waiting time to avoid this condition.

**Comment by Yanpas** [comment]
I suppose ccls may become stuck and `this.client.stop()` lasts longer than 4 seconds. So we must not await this Promise. Will open PR soon

**Comment by Will-GXZ** [comment]
By the way, for #30 , I think the client should send like "onsave" message to ccls when user do a "save operation". I did a global search on the source code, seems there is no such "textDocument/didSave" string.

**Comment by Will-GXZ** [comment]
Hi @Yanpas , after updating to the newest version of vscode-ccls and ccls, I start seeing this bug again. When I open a project, it has 3000 jobs in queue, and I call ccls:restart language server in lazy mode, sometimes it doesn't terminate the previous ccls session.

**Comment by Yanpas** [comment]
You were using master? Can you attach logs?

Maybe lsl stop method doesn't terminate it immediately...

**Comment by Will-GXZ** [comment]
> You were using master? Can you attach logs?
> 
> Maybe lsl stop method doesn't terminate it immediately...

Yes I'm using master. Now close vscode will terminate ccls, but manually restart server will just create a new session. 

### Log:
------------
09:48:31                initialize.cc:364 I start 8 indexers
09:48:31                initialize.cc:372 I dispatch initial index requests
09:48:31              sema_manager.cc:717 I create session for a.cpp
09:48:31                  pipeline.cc:452 I loaded project. Refresh semantic highlight for all working file.
09:48:31                  pipeline.cc:279 I load cache for a.cpp
09:48:31                  pipeline.cc:279 I load cache for b.cpp
09:48:56              sema_manager.cc:717 I create session for c.cpp
Restarting ccls, lazy mode off
09:49:04                initialize.cc:278 I initialize in directory xxxx/xxx/xx
09:49:04                initialize.cc:301 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabas xxxxxxxxx
---------------

After I restart ccls in lazy mode, the previous session is still alive.

**Comment by Yanpas** [comment]
I cannot reproduce this issue. The only thing that I've noticed that ccls may reply on stop (`this.client.stop`) request and terminate for a long time. That usually happens when it has a lot of jobs to do.

@MaskRay What do you think about `exit(0);` in ccls in stdin thread on stop message? Or at least wait for all active jobs in threadpool, discard those one in the queue.

**Comment by Will-GXZ** [comment]
> I cannot reproduce this issue. The only thing that I've noticed that ccls may reply on stop (`this.client.stop`) request and terminate for a long time. That usually happens when it has a lot of jobs to do.
> 
> @MaskRay What do you think about `exit(0);` in ccls in stdin thread on stop message? Or at least wait for all active jobs in threadpool, discard those one in the queue.

Yes, seems like it only happens when ccls has a heavy load. I do notice that sometimes it take a long time for ccls to quit, but sometimes ccls just doesn't quit.

**Comment by Yanpas** [comment]
> I think this is a regression, it would be great if you guys can take a look.

here what happens. Vscode extension send request to stop. If server responds in 200ms it (extension) doesn't do anything. Otherwise it sends SIGTERM signal. I don't think it's a good idea to kill process anyway.

**Comment by Will-GXZ** [comment]
OK, seems like it's an issue with server side. I'm going to change my
script to generate workspace to enable lazy mode by default to avoid this
situation.

**Comment by Yanpas** [comment]
@MaskRay 
Here is what may be implemented on the server side:
```cpp
// receive exit message
std::thread t([]() {
  std::this_thread::sleep_for(std::chrono::milliseconds(100));
  std::exit(10);
};
t.detach();
```

**Comment by MaskRay** [comment]
When ccls receives the [`"exit"` notification](https://microsoft.github.io/language-server-protocol/specification#exit), the main thread waits for all threads to finish their jobs then exit. The mechanism was added since #159.

I am not sure 200ms (reference?) is sufficient in every scenario. Note that when an indexer thread builds preamble for a large file with many `#include`s, it may take seconds. The thread may just open a cache file and start writing, forcing it to exit is not good.

**Comment by Yanpas** [comment]
> the main thread waits for all threads to finish their jobs then exit. 

If thread pool has 1000 jobs and 10 threads will it wait for current 10 jobs to finish or all 1000?

**Comment by MaskRay** [comment]
> If thread pool has 1000 jobs and 10 threads will it wait for current 10 jobs to finish or all 1000?

See my updated comment. Their *current* job, not *all jobs*. The latter is apparently infeasible.

```cpp
    if (pipeline::quit.load(std::memory_order_relaxed))
      break;
```
