### ISSUE TITLE
Hover doesn't work for new edited statements.

### ISSUE THREAD

**Issue by Will-GXZ** [MaskRay/vscode-ccls#30]
I recently noticed that hover doesn't work for the code I just added. Saving the file doesn't solve the problem, I need to manually close and re-open the file to make hover work. I'm not sure if this is a bug or I'm not following the right behavior.

**Comment by MaskRay** [comment]
> hover doesn't work for the code I just added.

This is by design: `textDocument/hover` requests are served by index (`query.h` `struct DB;`). By default, the initialization option (see https://github.com/MaskRay/ccls/wiki/Customization#initialization-options) `index.onChange` is false and the index is updated after you save the document (which triggers the language client to send `textDocument/didSave`).

Can you append `-log-file=/tmp/ccls.log` to your ccls command line (recommended to use a [shell script wrapper](https://github.com/MaskRay/ccls/wiki/Install#shell-script-wrapper)) and check whether the three lines are appended when you save the document?

```
timestamp changed for /tmp/c/a.cc
parse /tmp/c/a.cc
store index for /tmp/c/a.cc
```

**Comment by Will-GXZ** [comment]
> > hover doesn't work for the code I just added.
> 
> This is by design: `textDocument/hover` requests are served by index (`query.h` `struct DB;`). By default, the initialization option (see https://github.com/MaskRay/ccls/wiki/Customization#initialization-options) `index.onChange` is false and the index is updated after you save the document (which triggers the language client to send `textDocument/didSave`).
> 
> Can you append `-log-file=/tmp/ccls.log` to your ccls command line (recommended to use a [shell script wrapper](https://github.com/MaskRay/ccls/wiki/Install#shell-script-wrapper)) and check whether the three lines are appended when you save the document?
> 
> ```
> timestamp changed for /tmp/c/a.cc
> parse /tmp/c/a.cc
> store index for /tmp/c/a.cc       # the index has been updated with the change. New textDocument/hover requests should return updated results
> ```
> Also, please include more information for your issue: OS, editor (implied from where you reported the issue), version, minimum reproduce (code snippet+interactive actions), screenshot/screencast (sometimes more useful than text), etc

Yes, I know index.onChange is false, so I tried manually save the file, but the hover for the added part is not working until I re-open the file.

---
My environment:
OS: MacOS: 10.13.6
ccls: version 7.0.1 (tags/RELEASE_701/final)
vscode-ccls: 0.1.19
vscode: 1.30.2

---
I will try the log thing later.

**Comment by Will-GXZ** [comment]
OK, I see. Are you observing the same issue? Maybe it's a problem with vscode-languageclient?

**Comment by Yanpas** [comment]
Yes, I face the same issue

**Comment by MaskRay** [comment]
I cannot reproduce this with neovim + coc.nvim

```zsh
print 'int main(){foo();}' > a.cc; print 'int foo();' > a.h
```

1. open `a.cc`
2. insert `#include "a.h"`, save
3. `textDocument/hover` on `foo();` works

**Comment by Will-GXZ** [comment]
> I cannot reproduce this with neovim + coc.nvim
> 
> ```shell
> print 'int main(){foo();}' > a.cc; print 'int foo();' > a.h
> ```
> 
> 1. open `a.cc`
> 2. insert `#include "a.h"`, save => client sends `textDocument/didSave` => server logs `timestamp changed for /tmp/c/a.cc`, `parse /tmp/c/a.cc`, `store index for /tmp/c/a.h` and `store index for /tmp/c/a.cc`
> 3. `textDocument/hover` on `foo();` works

In my case, click "command+s" manually saving the file doesn't trigger client to send "textDocument/didSave". I do specify the right "compile_commands.json".

**Comment by Will-GXZ** [comment]
After updating to the newest version(Master HEAD), it works.
