### ISSUE TITLE
Syntactic highlighting not working

### ISSUE THREAD

**Issue by jamespfeffer** [MaskRay/vscode-ccls#35]
I can't get syntactic highlighting to work.  I don't have any extensions other than ccls installed and I have this very simple settings file:
```
{
    "ccls.highlighting.bold.macros": true,
    "ccls.highlighting.bold.freeStandingVariables": true,
    "ccls.highlighting.bold.freeStandingFunctions": true
}
```

Is there something else I need to add?

**Comment by Yanpas** [comment]
Confirm, there are issues with this, will fix later

**Comment by Yanpas** [comment]
Fixed in improv_2 branch
![image](https://user-images.githubusercontent.com/7345761/51570230-9639ef00-1eaf-11e9-9bc6-da0253cb6463.png)

I guess color should be empty arrays by default, 

![image](https://user-images.githubusercontent.com/7345761/51570375-ee70f100-1eaf-11e9-859f-4104a86eb363.png)
