### ISSUE TITLE
Visual Studio Code 1.30 loading error with ObjC

### ISSUE THREAD

**Issue by nilsnilsnils** [MaskRay/vscode-ccls#38]
Don't work with 1.30 

1. Failed to start ccls with command "ccls".
2. Couldn't start client ccls

**Comment by MaskRay** [comment]
Please give more details about your environment: OS, compiler vercion, clang version, ccls version... and the reproduce instructions. https://github.com/MaskRay/vscode-ccls/issues/30#issuecomment-455610611 is a good example

**Comment by nilsnilsnils** [comment]
My environment:
OS: MacOS: 10.14.2 (18C54)
vscode-ccls: 0.1.19
vscode: Version 1.30.2 (1.30.2)

Reproduce:
Open the following file result in Error message
[Uploading Test.m.zip…]()

Error message:
![bildschirmfoto 2019-01-28 um 08 17 05](https://user-images.githubusercontent.com/5464118/51820187-3e4b2000-22d5-11e9-8e27-4d0f3f73e26e.png)
