### ISSUE TITLE
consider not displaying inline namespaces like __cxx11

### ISSUE THREAD

**Issue by joelhock** [MaskRay/vscode-ccls#43]
this is a small deal, so feel free to close this issue with "won't fix", but the `__cxx11` inline namespace used by recent libstdc++ https://greek0.net/blog/2016/10/29/gcc_compatibility/ is ugly whenever it shows up in `std::string` and `std::list`.

call my project crazy (or we get what we deserve), but our codebase `using namespace std;` as a general rule.
```c++
string mystring;
mystring = "asdf"; 
```
hover over the `mystring` in the second line gives type `std::__cxx11::string g`

even if you don't `using namespace std;`, then 
```c++
std::string mystring;
mystring = "adsf";
```
hover over `string` in the first line gives `typedef basic_string<char> std::__cxx11::string`

unless you're familiar with what's going on, the `__cxx11` is a bit surprising, and if you are familiar, it's just additional noise.  I'm not sure if inline namespaces in general could be removed, or if just getting rid of `__cxx11` is the right call...or maybe doing nothing is.

**Comment by MaskRay** [comment]
Does this patch have any downside?

```diff
diff --git i/src/indexer.cc w/src/indexer.cc
--- i/src/indexer.cc
+++ w/src/indexer.cc
@@ -490,6 +490,7 @@ public:
     PP.PolishForDeclaration = true;
     PP.ConstantsAsWritten = true;
     PP.SuppressTagKeyword = true;
+    PP.SuppressUnwrittenScope = true;
     PP.SuppressInitializers = true;
     PP.FullyQualifiedName = false;
     return PP;
```

```cpp
  /// Suppress printing parts of scope specifiers that don't need
  /// to be written, e.g., for inline or anonymous namespaces.
  unsigned SuppressUnwrittenScope : 1;
```

**Comment by joelhock** [comment]
that patch works like a charm for this situation, and I don't notice any downsides.

**Comment by MaskRay** [comment]
`SuppressUnwrittenScope defaults to true` since https://github.com/MaskRay/ccls/pull/315
