### ISSUE TITLE
Support code folding

### ISSUE THREAD

**Issue by ingjieye** [MaskRay/vscode-ccls#45]

**Comment by MaskRay** [comment]
ccls supports `textDocument/foldingRange` may some people feel the vscode native folding feature it good enough and would like to set initialization option `capabilities.foldingRangeProvider` to false.

Anyway, this is a bad feature request as at least more information should be provided.

**Comment by abyss7** [comment]
What kind of additional information do you need? - As a user I can see, that in an auto-mode Folding Strategy this extension doesn't provide any folding markers to editor (don't really know how it should work under the hood). Indentation mode is good, but not perfect for all code-styles.

**Comment by GitMensch** [comment]
Necromance... I've just:
* installed ccls via `apt`
* installed ccls via marktplace

I now see a reasonable outline, go to, ... and for not active code paths (`#ifdef`) the style is "all grey".

But I can't fold those inactive preprocessor areas - how to do that?
Also not possible: fold code blocks other than functions (which seems to be the sole part [along with struct definitions] where folding currently works), for example if/else, while, ...

Maybe that's just "hidden" behind an option?
If not: would you mind reopening this issue?
