### ISSUE TITLE
"ccls.cache.directory" is ignored.

### ISSUE THREAD

**Issue by neonmori** [MaskRay/vscode-ccls#49]
With `"ccls.cache.directory"` set to `/tmp/.ccls-cache`, all the ccls index files are still generated in `${workspaceFolder}/.ccls-cache`. Plus it would be much nicer if this extension can have a change log.

**Comment by MaskRay** [comment]
It requires the latest version of ccls (https://github.com/MaskRay/ccls/commit/2fc2d1b16ca239f4d56ced02cbdb885ef345dce1)

https://github.com/MaskRay/ccls/wiki/Customization#initialization-options
