### ISSUE TITLE
Config for disabling ccls code lens

### ISSUE THREAD

**Issue by WesleyYue** [MaskRay/vscode-ccls#54]
Is there a way to disable the code lens feature only for ccls? I'd like to keep code lens enabled at the editor level for other extensions, and only disable the ccls parts of the code lens.

**Comment by MaskRay** [comment]
https://github.com/MaskRay/vscode-ccls/pull/52 `ccls.codeLens.enabled`

**Comment by WesleyYue** [comment]
Thanks. I see that the PR was merged 6 days ago, and I don't currently see it in my installed version of vscode-ccls. I'm not super familiar with how vscode extensions are updated. Do I need to wait for a new version to be published, or is there a way I can pull the master branch now?
