### ISSUE TITLE
Trouble getting the outline to work

### ISSUE THREAD

**Issue by guzzard** [MaskRay/vscode-ccls#57]
Hi, thanks for ccls, it's awesome!

I'm having trouble though getting the outline to work in vscode. Everything else seem to work fine.
![image](https://user-images.githubusercontent.com/9007314/54083624-27610a00-4326-11e9-983b-8cdd1c14c391.png)

I don't see any errors in the log etc, what might I be missing?

### System information

* ccls version: 20190309-1 (ccls-git from AUR)
* OS: Arch Linux
* Editor: 1.32.1
* vscode-ccls version: 0.1.26

**Comment by MaskRay** [comment]
Please update `aur/ccls`. It has been fixed
