### ISSUE TITLE
Plans to support a remote extension?

### ISSUE THREAD

**Issue by suo** [MaskRay/vscode-ccls#59]
Recently VS Code [announced](https://code.visualstudio.com/blogs/2019/05/02/remote-development) that they adding support for remote development. This requires that extensions be updated to work properly in a remote workspace. Are there plans to update vscode-ccls to do this?

**Comment by Riatre** [comment]
Hello,

Have you tried installing and using vscode-ccls in such environment? As we didn't do any special thing listed in [their documentation](https://code.visualstudio.com/api/advanced-topics/remote-extensions), I expect that vscode-ccls should work fine.

**Comment by suo** [comment]
It appears to work! I had a different quirk that was causing results to be unavailable. Thanks for the response.
