### ISSUE TITLE
C++ Static variables are rendered as global variables

### ISSUE THREAD

**Issue by flar** [MaskRay/vscode-ccls#62]
I have the following settings in my config file for static methods and variables as well as global variables. ccls classifies the static variables as globals and ignores the settings for them:

```
    "ccls.highlighting.enabled.staticMemberFunctions": true,
    "ccls.highlighting.colors.staticMemberFunctions": [ "#0000c0" ],
    "ccls.highlighting.enabled.staticMemberVariables": true,
    "ccls.highlighting.colors.staticMemberVariables": [ "#00ff00" ],
    "ccls.highlighting.enabled.globalVariables": true,
    "ccls.highlighting.colors.globalVariables": [ "#806000" ],
```

For grins I made the following edit to indexer.cc and the static variables started showing up as static methods, but I couldn't find an appropriate SymbolKind value to map to the static variable settings in the config file.

```
diff --git a/src/indexer.cc b/src/indexer.cc
index 066fc9f1..a1bd8d16 100644
--- a/src/indexer.cc
+++ b/src/indexer.cc
@@ -202,7 +202,11 @@ Kind GetKind(const Decl *D, SymbolKind &kind) {
     // ccls extension
     kind = SymbolKind::Parameter;
     return Kind::Var;
-  case Decl::Var:
+  case Decl::Var: {
+    const auto *VD = cast<VarDecl>(D);
+    kind = VD->isStaticDataMember() ? SymbolKind::StaticMethod : SymbolKind::Variable;
+    return Kind::Var;
+  }
   case Decl::Decomposition:
     kind = SymbolKind::Variable;
     return Kind::Var;
```

**Comment by MaskRay** [comment]
These non-local variables and static local variables have static storage duration. I don't see any problem behaving this way..

**Comment by jim-flar** [comment]
Why provide the configuration parameters to highlight them separately then? Semantically they are associated with a class even if their storage properties match other variables.

**Comment by findNextStep** [comment]
when we has some code like 
```cpp
class testclass{
    static void testfunc(){
        int var;
    }
};
```
the `testclass::testfunc::var` is not a global var but will rander as a global var
can see
![image](https://user-images.githubusercontent.com/26270464/66727071-7a2c1280-ee6f-11e9-8d77-13ae82ee775f.png)

**Comment by MaskRay** [comment]
Can you try the latest ccls and https://github.com/MaskRay/vscode-ccls/pull/75?

**Comment by findNextStep** [comment]
it seem to work just fine , but I don`t know how to set underline
here is my setting 
```json
{
    "ccls.clang.extraArgs": [
        "-isystem",
        "/Library/Developer/CommandLineTools/usr/include/c++/v1",
    ],
    "ccls.clang.resourceDir": "/usr/local/Cellar/llvm/9.0.0/lib/clang/9.0.0",
    "ccls.launch.args": [
        "-log-file=/tmp/ccls_test.log",
        "--init={\"capabilities\": {\"foldingRangeProvider\": false}}",
    ],
    "ccls.highlight.type.face": ["enabled"],
    "ccls.highlight.type.colors": [ "#dd82bc", ],
    "ccls.highlight.function.face": ["enabled"],
    "ccls.highlight.function.colors": [ "#a36526", ],
    "ccls.highlight.variable.face": ["enabled"],
    "ccls.highlight.variable.colors": [ "#ff0000" ],
    "ccls.highlight.macro.colors": [ "#00ff00" ],
    "ccls.highlight.namespace.colors": [ "#0000f0", ],
    "ccls.highlight.parameter.face": [ "variable" ],
    "ccls.highlight.typeAlias.face": [
        "type",
        "macro",
    ],
    "ccls.highlight.global.face": [
        "fontWeight: bolder"
    ],
    "ccls.highlight.member.face": [
        "fontStyle: underline"
    ],
    "ccls.highlight.enum.face": [
        "fontStyle: italic",
    ],
    "ccls.highlight.static.face": [
        "fontStyle: italic"
    ],
    "ccls.highlight.globalVariable.face": [
        "global"
    ]
}
```
here is how it look like
![image](https://user-images.githubusercontent.com/26270464/66751190-03b80080-eec1-11e9-80c3-1d331ae92470.png)
it will be better that can compatible with previous vscode setting temporary，will this update push to brew-ccls ?

**Comment by MaskRay** [comment]
> "fontStyle: underline"

Try `"ccls.highlight.member.face": ["textDecoration: underline"]`
See https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration

Merged the change and published 0.1.28 (https://marketplace.visualstudio.com/items?itemName=ccls-project.ccls)

**Comment by gggin** [comment]
Old style style can set `freeStandingFunctions` 's color, but now I can not find a way to set that.

**Comment by MaskRay** [comment]
> Old style style can set freeStandingFunctions 's color, but now I can not find a way to set that.

```jsonc
"ccls.highlight.function.colors": [ "#a36526", ],
"ccls.highlight.memberFunction.colors": [ "#a36526", ],
"ccls.highlight.staticMemberFunction.colors": [ "#a36526", ],
```

**Comment by gggin** [comment]
Sorry for ask question again but a new issue is bad.

Old style can set enum color ( the enum type color not enumConstValue)
but new color style
```
"ccls.highlight.enum.face" 
```
only means the enumConstValue

So I cannot make different color with enum types and default Class types
