### ISSUE TITLE
Consider using absolute cache directory by default

### ISSUE THREAD

**Issue by jhasse** [MaskRay/vscode-ccls#63]
While putting `.ccls-cache` in the global gitignore fixes the problem for Git, some tools (e.g. Xcode) are still indexing those files. There are also projects which glob files in their project source directory recursively.

Considering the excellent support for absolute cache directories, my suggestion would be to use

* `${env:HOME}/.cache/ccls-cache` on Linux,
* `${env:TMPDIR}/ccls-cache` on macOS,
* and `${env:TEMP}/ccls-cache` on Windows.

See also #16.

**Comment by MaskRay** [comment]
The wiki is under-documented but ccls.cache.directory is clear described at https://github.com/MaskRay/ccls/wiki/Visual-Studio-Code#cclscachedirectory

My feeling is still that we should try using the same default value on all clients and all platforms.
This way,

> The cache directory can be shared among clients: you can index your project in vscode or with ccls -index and reuse it in Emacs, Vim, Atom, ...

**Comment by jhasse** [comment]
That should still be possible with an absolute path, shouldn't it?

**Comment by jhasse** [comment]
Why did you close the issue?

**Comment by MaskRay** [comment]
I think users should specify `${env:TMPDIR}/ccls-cache` or the like.

Or use

```
% cat ~/.config/git/ignore
.ccls-cache
.ccls-root
```

**Comment by jhasse** [comment]
Thanks for the explanation. The thing about adding it to global gitignore, is that this is another configuration step the user has to remember (and then there's the one time where you open a Mercurial repository ...). All those little config gotchas are holding ccls back in my opinion.
