### ISSUE TITLE
How can I disable auto-format?

### ISSUE THREAD

**Issue by unnamed42** [MaskRay/vscode-ccls#65]
I have found no option to disable or configure auto-formatting, and by default `}` triggers it.
Maybe initialization options `firstTriggerCharacter` and `moreTriggerCharacter` are related? They are not documented by the way.

**Comment by MaskRay** [comment]
If you send the following initialization options to ccls, it will not send `"firstTriggerCharacter":"}"` to the language client.

```javascript
{
  "capabilities": {
    "documentOnTypeFormattingProvider": {
      "firstTriggerCharacter": ""
    }
  }
}
```
