### ISSUE TITLE
Avoid showing Error warning discoverd by ccls

### ISSUE THREAD

**Issue by steinemann** [MaskRay/vscode-ccls#69]
Hi,

I use ccls and the visual studio code plugin to work with a big codebase.

As we use a lot of macros in c++, it's common to write

MYMACRO(....);

Unfortunately the semicolon at the end of this usage produced an empty expression statement.
ccls detects this and produces a lot of warning, that are shown like 

"empty expression statement has no effect; remove unnecessary ';' to silence this warning ccls(4) [...]"

Is it possible to somehow avoid showing this specific message ?

Thanks

**Comment by MaskRay** [comment]
This is a clang specific diagnostic.

Add `-Wno-extra-semi-stmt` to your cxxflags and regenerate `compile_commands.json`.
