### ISSUE TITLE
Show Cross Reference Not Works Correctly

### ISSUE THREAD

**Issue by ExiaHan** [MaskRay/vscode-ccls#70]
Hello, 
I met some problems when using ccls. I've already disable all related extensions like global and MS-C++ extension except vscode-ccls.

### Expected behavior

1. Seems run the command "ccls show cross reference" not works correctly but Shift+F12 or directly click the N-ref button will work.
2. ccls/reload will always failed

### Steps to reproduce
![ccls](https://user-images.githubusercontent.com/4057890/65425087-be635e80-de3f-11e9-9641-ef7db19f3e0f.gif)

In the pic, 
1. The first is to click 2refs button before function, it works.
2. Then directly use the command, failed
3. Finally Shift+F12, works

At the end, try to do ccls/reload. Failed.

### System information

* ccls version (`git describe --tags`): 0.20190823
* OS:  ArchLinux
* Editor:  vscode
* vscode-ccls version (`git describe --tags`): 0.1.26 from vscode extension market

**Comment by MaskRay** [comment]
This command (`ccls.call`) invokes [`$ccls/call`](https://github.com/MaskRay/ccls/wiki/FAQ#cclscall) to fetch callers/callees. Can you reproduce the in a minimal source file?

```cpp
      {
        "title": "Show Cross References",
        "category": "ccls",
        "command": "ccls.call"
      },
```

**Comment by MaskRay** [comment]
Can't reproduce the `$ccls/reload` issue as you described. You might use either a stale ccls or a stale vscode-ccls...
