### ISSUE TITLE
Semantic highlighting color setting?

### ISSUE THREAD

**Issue by mkitby** [MaskRay/vscode-ccls#71]
I enable the Semantic highlighting according to https://github.com/MaskRay/ccls/wiki/Visual-Studio-Code, but seems the highlight color is random, it shows different color even if the symbol is the same 

```
"ccls.highlighting.enabled.types": true,
"ccls.highlighting.enabled.freeStandingFunctions": true,
"ccls.highlighting.enabled.memberFunctions": true,
"ccls.highlighting.enabled.freeStandingVariables": true,
"ccls.highlighting.enabled.memberVariables": true,
"ccls.highlighting.enabled.namespaces": true,
"ccls.highlighting.enabled.macros": true,
"ccls.highlighting.enabled.enums": true,
"ccls.highlighting.enabled.typeAliases": true,
"ccls.highlighting.enabled.enumConstants": true,
"ccls.highlighting.enabled.staticMemberFunctions": true,
"ccls.highlighting.enabled.parameters": true,
"ccls.highlighting.enabled.templateParameters": true,
"ccls.highlighting.enabled.staticMemberVariables": true,
"ccls.highlighting.enabled.globalVariables": true,

"C_Cpp.autocomplete": "Disabled",
"C_Cpp.formatting": "Disabled",
"C_Cpp.errorSquiggles": "Disabled",
"C_Cpp.intelliSenseEngine": "Disabled",
```

Macro definition, 

![image](https://user-images.githubusercontent.com/15389150/65585578-44ed7c80-dfb5-11e9-96db-95b6edb7eb6c.png)

Function call,
![image](https://user-images.githubusercontent.com/15389150/65585706-7d8d5600-dfb5-11e9-99f2-833fab89a1e2.png)

**Comment by findNextStep** [comment]
set `ccls.highlighting.colors.*`work for me
if you use auto complete to create the setting, you can see why It`s random
