### ISSUE TITLE
.ccls file in project root not read?

### ISSUE THREAD

**Issue by skelutten** [MaskRay/vscode-ccls#72]
Here are some things you should try before filing a bug report:

+ This is for client side issues. For server side issues, report at [ccls](https://github.com/MaskRay/ccls) or [vscode-ccls](https://github.com/MaskRay/vscode-ccls).
+ Check https://github.com/MaskRay/ccls/wiki/Visual-Studio-Code
+ Check https://github.com/MaskRay/ccls/wiki/Debugging
+ Check [the FAQ](https://github.com/MaskRay/ccls/wiki/FAQ) to see if your issue is mentioned.

If none of those help, remove this section and fill out the four sections in the template below.

---

### Observed behavior
I expect the .ccls file to be read and used, but it seems it isn't as include files are not found 
If I instead add the same info to ccls.clang.extraArgs in settings.json then most include paths are found.

### Expected behavior

The info in the .ccls file in project root should be used.

### Steps to reproduce

1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.

### System information
/home/$USER/.linuxbrew/Cellar/ccls/0.20190823.3 (5 files, 28.1MB) *
  Built from source on 2019-10-08 at 14:31:57

* OS: 
RedHat
* Editor: 
* vscode-ccls version (`git describe --tags`): 0.1.26

**Comment by skelutten** [comment]
It actually seems like "-I/x/y/z" can't be in .ccls but have to be settings.json

**Comment by joelhock** [comment]
what is in your `.ccls` file?  I use `-I` settings extensively in mine.  keep in mind the first line of the .ccls file is the driver, which usually should be `clang`.  so, e.g. my `.ccls` file looks like:
```
clang
-include
src/gccext/force_include
-I
atl/src/gccext
-I
src/foo
-isystem
src/3ps
```
