### ISSUE TITLE
diagnostic won't disappear even if the file has been deleted

### ISSUE THREAD

**Issue by Abbyyan** [MaskRay/vscode-ccls#89]
When i open a file and it has some error showed in the vscode `PROBLEMS` window. But when i delete the file and refresh the vscode file system, the`PROBLEMS` for the deleted file still exist. May be it will be better to close the `PROBLEMS ` when the related file has been deleted.  Will it be realized in the future ? Thanks a lot . @MaskRay 
![image](https://user-images.githubusercontent.com/12140508/76535329-a4810b00-64b5-11ea-9894-1a24a2cfa16e.png)

**Comment by MaskRay** [comment]
This feels like a VSCode side issue to me. It should dismiss the diagnostics when it finds that a file is deleted...
