### ISSUE TITLE
Not getting ccls to work with a large codebase (Firefox)

### ISSUE THREAD

**Issue by SubhamoyS** [MaskRay/vscode-ccls#92]
This is not a problem I have faced only in the ccls plugin for vscode. Using ccls on sublime text 3 through the LSP plugin resulted in a similar error log (see log file posted below), but since the developers of sublime-LSP are not responsible for ccls, I have confined the text below only for vscode-ccls.

### The Premise

**Target codebase:** [Mozilla-Central](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Simple_Firefox_build/Linux_and_MacOS_build_preparation)
**Target system:** Ubuntu 18.10 with kernel 5.3.0-42-generic running on Ryzen 9 3900X
**VSCode settings:**
```
{
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "workbench.colorTheme": "Sublime Material Theme - Dark",
    "bookmarks.saveBookmarksInProject": true,
    "ccls.misc.compilationDatabaseDirectory": "obj-x86_64-pc-linux-gnu",
    "C_Cpp.autocomplete": "Disabled",
    "C_Cpp.formatting": "Disabled",
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseEngine": "Disabled",
    "ccls.clang.resourceDir": "/home/myusername/.mozbuild/clang/lib/clang/9.0.1",
    "ccls.index.blacklist": [
        "^/home/myusername/git/mozilla-unified/obj-x86_64-pc-linux-gnu",
        "^/home/myusername/git/mozilla-unified/obj-x86_64-pc-linux-gnu-debug"
    ],
    "ccls.diagnostics.spellChecking": false,
    "ccls.completion.detailedLabel": true,
    "ccls.completion.enableSnippetInsertion": true,
    "ccls.launch.args": ["-log-file=/tmp/ccls.log", "-v=1"],
}
```
The first 4 are irrelevant, I assume. I disabled things from the microsoft cpptools that could interfere with ccls. Since I am using mozilla toolchain instead of my system compiler, I had to set the resource directory. I have two build directories, one for debug and one for release. But I want ccls to take the compile_commands.json only from release. In some cases, the build system generates header and source files in the build directories. I want the indexer to not care about them at all.

The beginning of the compile_commands.json looks like [this](https://gist.github.com/SubhamoyS/e167d42f2baaa09ab310d591ff8a8bd9) and it was generated like [this](https://developer.mozilla.org/en-US/docs/Developer_Guide/Editor_Configuration#General).

**ccls version:** 0.20190823.5-18-g5a08ff99 (pulled and compiled from the current master using the same clang compiler from Mozilla toolchain)
**vscode-ccls version:** 0.1.28
**vscode version:** 1.43.0

### The Problem

There are various problems.

![principal](https://user-images.githubusercontent.com/13917237/77171123-4ad39e80-6abc-11ea-87a2-69ae7ea5059a.jpg)

Although this variable was declared two lines above, it is seen as an 'undeclared identifier'.

![nsiprincipal](https://user-images.githubusercontent.com/13917237/77171218-69399a00-6abc-11ea-895a-a37fdaa4a237.jpg)

Although ccls can pull inline documentation for a class, it thinks it is an undeclared identifier.

![references](https://user-images.githubusercontent.com/13917237/77171263-79517980-6abc-11ea-94e1-78256caf1b19.jpg)

Trying to find references gives me the header file as one entry, the source file as another entry, and then almost nothing else. I know for a fact that this method has been used profusely.

![autocomplete](https://user-images.githubusercontent.com/13917237/77171541-e2d18800-6abc-11ea-9dd5-c0ddea94b975.jpg)

Dot or arrow-based completion list is full of random things that have nothing to do with the object in question.

The log shows the clang has crashed for all worker/job threads, pretty much:

[ccls.log](https://github.com/MaskRay/vscode-ccls/files/4360071/ccls.log)

As I see it, this cannot be a general problem of the software. I must have configured things in a way that was not intended. Please help me troubleshoot the problem. Without ccls, getting a systemwide autocomplete on a codebase this large will be next to impossible.

**Comment by SubhamoyS** [comment]
Closed because I found an issue with how `compile_commands.json` is being generated, which is throwing ccls off.

**Comment by Murplugg** [comment]
> an issue with how `compile_commands.json` is being generated, which is throwing ccls off.

Been a good while but what was the issue and what did the solution look like?
